"""file upd

Revision ID: 30611abb48b8
Revises: e512fa917d49
Create Date: 2025-12-06 12:07:28.885832

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30611abb48b8"
down_revision = "5a2fc698db40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_change_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "profile_id",
            sa.BigInteger(),
            nullable=False,
            comment="ID профиля, который был изменен",
        ),
        sa.Column(
            "changed_by_eid",
            sa.BigInteger(),
            nullable=False,
            comment="EID сотрудника, который внес изменение",
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время изменения",
        ),
        sa.Column(
            "table_name",
            sa.String(length=50),
            nullable=False,
            comment="Название таблицы",
        ),
        sa.Column(
            "record_id", sa.BigInteger(), nullable=True, comment="ID записи в таблице"
        ),
        sa.Column(
            "field_name",
            sa.String(),
            nullable=False,
            comment="Название измененного поля",
        ),
        sa.Column(
            "old_value",
            sa.String(),
            nullable=True,
            comment="Старое значение (JSON или строка)",
        ),
        sa.Column(
            "new_value",
            sa.String(),
            nullable=True,
            comment="Новое значение (JSON или строка)",
        ),
        sa.Column(
            "operation",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="profileoperationtype"),
            nullable=False,
            comment="Тип операции",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_eid"],
            ["employee.eid"],
            name=op.f("fk_profile_change_log_changed_by_eid_employee"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
            name=op.f("fk_profile_change_log_profile_id_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_change_log")),
    )
    op.add_column("file", sa.Column("created_by", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "created_by")
    op.drop_table("profile_change_log")
    # ### end Alembic commands ###
